### ISSUE TITLE
ArrayIndexOutOfBoundsException from the HashMemoryCache

### ISSUE THREAD

**Issue by jejemontagne** [kevoree/kubi#4]
Available in the commit **[develop 66aa95c] Issue signalisation**

Conditions:
- comment all the plugins except the SmartFridge plugin (the plugin reading into the local file)
- launch the KubiRunner
  
  _Note : if the setter are commented, the execution runs without issues._

```
java.lang.ArrayIndexOutOfBoundsException: 738
    at org.kevoree.modeling.api.data.cache.HashMemoryCache.dirties(HashMemoryCache.java:92)
    at org.kevoree.modeling.api.data.manager.DefaultKDataManager.save(DefaultKDataManager.java:187)
    at org.kevoree.modeling.api.abs.AbstractKModel.save(AbstractKModel.java:63)
    at org.kubi.plugins.smartfridge.SmartFridgePlugin$1.on(SmartFridgePlugin.java:52)
    at org.kubi.plugins.smartfridge.SmartFridgePlugin$1.on(SmartFridgePlugin.java:25)
    at org.kevoree.modeling.api.abs.AbstractKDefer$1.run(AbstractKDefer.java:104)
    at org.kevoree.modeling.api.abs.AbstractKDefer.informParentEnd(AbstractKDefer.java:60)
    at org.kevoree.modeling.api.abs.AbstractKDefer.setDoneOrRegister(AbstractKDefer.java:34)
    at org.kevoree.modeling.api.abs.AbstractKDeferWrapper$1.on(AbstractKDeferWrapper.java:21)
    at org.kevoree.modeling.api.data.manager.DefaultKDataManager$6.on(DefaultKDataManager.java:414)
    at org.kevoree.modeling.api.data.manager.DefaultKDataManager$6.on(DefaultKDataManager.java:409)
    at org.kevoree.modeling.api.data.manager.LookupAllRunnable$1$1$1.on(LookupAllRunnable.java:80)
    at org.kevoree.modeling.api.data.manager.LookupAllRunnable$1$1$1.on(LookupAllRunnable.java:66)
    at org.kevoree.modeling.api.data.manager.DefaultKDataManager.bumpKeysToCache(DefaultKDataManager.java:605)
    at org.kevoree.modeling.api.data.manager.LookupAllRunnable$1$1.on(LookupAllRunnable.java:66)
    at org.kevoree.modeling.api.data.manager.LookupAllRunnable$1$1.on(LookupAllRunnable.java:51)
    at org.kevoree.modeling.api.data.manager.DefaultKDataManager.bumpKeysToCache(DefaultKDataManager.java:605)
    at org.kevoree.modeling.api.data.manager.LookupAllRunnable$1.on(LookupAllRunnable.java:51)
    at org.kevoree.modeling.api.data.manager.LookupAllRunnable$1.on(LookupAllRunnable.java:40)
    at org.kevoree.modeling.api.data.manager.DefaultKDataManager.bumpKeysToCache(DefaultKDataManager.java:605)
    at org.kevoree.modeling.api.data.manager.LookupAllRunnable.run(LookupAllRunnable.java:40)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by jejemontagne** [comment]
This error is thrown also lines : 
- 98 (_org.kevoree.modeling.api.data.cache.HashMemoryCache.dirties(HashMemoryCache.java:98)_)
- 105 (_org.kevoree.modeling.api.data.cache.HashMemoryCache.dirties(HashMemoryCache.java:105)_)
